# Generated by Django 2.1 on 2018-08-21 00:09

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicearea',
            name='polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(default=None, srid=4326),
            preserve_default=False,
        ),
    ]
